# Generated by Django 5.2.4 on 2025-08-24 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('birth_date', models.DateField()),
                ('email', models.TextField()),
                ('phone_number', models.CharField(max_length=15)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
